import { useMemo, useState } from 'react';
import { api } from '../../api';
import type { AnalyzerRun, Finding } from '../../types';
import { analyzerName, findingLocation } from '../../lib/format';
import { useLoad } from '../../hooks/useLoad';
import { Empty, ErrorPanel, SummaryCard } from '../../components/ui';
import { SkeletonCards, SkeletonLines, SkeletonTable } from '../../components/skeletons';
import { FindingPreviewDialog } from '../../components/dialogs';

export type FindingFilter = { severity: string; category: string; analyzer: string; path: string; status: string; q: string };

export function ReportView({ scanId }: { scanId: string }) {
  const report = useLoad(() => api.report(scanId), [scanId]); const [filters, setFilters] = useState<FindingFilter>({ severity: '', category: '', analyzer: '', path: '', status: '', q: '' }); const [filtersOpen, setFiltersOpen] = useState(false); const [offset, setOffset] = useState(0); const [limit, setLimit] = useState(25); const [previewFinding, setPreviewFinding] = useState<Finding>(); const params = useMemo(() => ({ ...filters, limit: String(limit), offset: String(offset), sort: 'severity' }), [filters, limit, offset]); const findings = useLoad(() => api.findings(scanId, params), [scanId, ...Object.values(params)]);
  const list = findings.data?.items ?? [];
  const updateFilters = (next: FindingFilter) => { setFilters(next); setOffset(0); };
  if (report.loading) return <section className="report"><SkeletonCards count={4} /><SkeletonLines lines={3} /></section>; if (report.error) return <ErrorPanel error={report.error} retry={report.reload} />;
  const data = report.data!;
  const activeFilterCount = Object.values(filters).filter(Boolean).length;
  const clearFilters = () => updateFilters({ severity: '', category: '', analyzer: '', path: '', status: '', q: '' });
  const noFindingsTitle = filters.analyzer ? `${analyzerName(filters.analyzer)} reported no findings` : 'No findings match these filters';
  const noFindingsCopy = filters.analyzer ? 'This analyzer completed without reportable issues for the selected files.' : 'Try clearing one or more filters.';
  return <section className="report"><header className="report-header"><div><p className="eyebrow">Report</p><h2>Analysis overview</h2><p>{data.warnings?.length ? 'Analysis completed with limitations.' : 'Analysis completed.'}</p></div><a className="button secondary" href={api.markdownUrl(scanId)}>Export Markdown</a></header>{data.warnings?.length ? <div className="inline-warning"><strong>Incomplete analysis</strong>{data.warnings.map((warning) => <span key={warning}>{warning}</span>)}</div> : null}<section className="summary-grid"><SummaryCard label="Total findings" value={data.scan.total_findings ?? 0} /><SummaryCard label="New" value={data.comparison?.new_count ?? data.scan.new_count ?? 0} /><SummaryCard label="Fixed" value={data.comparison?.fixed_count ?? 0} /><SummaryCard label="Persistent" value={data.comparison?.persistent_count ?? 0} /></section><AnalyzerResults runs={data.scan.analyzer_runs} findings={data.findings} selectedAnalyzer={filters.analyzer} onSelect={(analyzer) => updateFilters({ ...filters, analyzer: filters.analyzer === analyzer ? '' : analyzer })} /><section className="findings-section"><div className="section-head"><div><h2>Findings</h2><p>Filter results without leaving the report.</p></div><div className="findings-toolbar"><button className="button secondary" aria-expanded={filtersOpen} aria-controls="finding-filters" onClick={() => setFiltersOpen((open) => !open)}>Filters{activeFilterCount ? ` (${activeFilterCount})` : ''}</button>{activeFilterCount ? <button className="text-button" onClick={clearFilters}>Clear</button> : null}</div></div>{filtersOpen && <FindingFilters filters={filters} setFilters={updateFilters} analyzers={data.scan.analyzer_runs} />}<div className="finding-list">{findings.loading ? <SkeletonTable rows={5} cols={5} className="findings-table" /> : findings.error ? <ErrorPanel error={findings.error} retry={findings.reload} /> : list.length ? <FindingsTable findings={list} onPreview={setPreviewFinding} /> : <Empty title={noFindingsTitle}>{noFindingsCopy}</Empty>}</div>{findings.data && <FindingsPagination total={findings.data.total} offset={findings.data.offset} limit={findings.data.limit} hasMore={findings.data.has_more} onLimit={(next) => { setLimit(next); setOffset(0); }} onPrevious={() => setOffset(Math.max(0, offset - limit))} onNext={() => findings.data?.next_offset !== undefined && setOffset(findings.data.next_offset)} />}</section>{previewFinding && <FindingPreviewDialog scanId={scanId} finding={previewFinding} onClose={() => setPreviewFinding(undefined)} />}</section>;
}

function AnalyzerResults({ runs, findings, selectedAnalyzer, onSelect }: { runs?: AnalyzerRun[]; findings?: Finding[]; selectedAnalyzer: string; onSelect: (analyzer: string) => void }) {
  if (!runs?.length) return null;
  return <section className="analyzer-results" aria-labelledby="analyzer-results-title"><div className="section-head"><div><h2 id="analyzer-results-title">Analyzer results</h2><p>Every completed check is shown. Select one to filter the combined report.</p></div></div><div className="analyzer-result-list">{runs.map((run) => { const count = findings ? findings.filter((finding) => finding.analyzer_id === run.analyzer_id).length : undefined; const selected = selectedAnalyzer === run.analyzer_id; const status = run.status === 'succeeded' ? 'success' : run.status; return <button type="button" className={`analyzer-result ${selected ? 'selected' : ''}`} aria-pressed={selected} key={run.analyzer_id} onClick={() => onSelect(run.analyzer_id)}><span><strong>{analyzerName(run.analyzer_id)}</strong><small>{run.status === 'succeeded' && count === 0 ? 'Completed with no findings' : run.message || run.status}</small></span><span className={`state ${status}`}>{count === undefined ? 'Results unavailable' : `${count} ${count === 1 ? 'finding' : 'findings'}`}</span></button>; })}</div></section>;
}

function FindingFilters({ filters, setFilters, analyzers }: { filters: FindingFilter; setFilters: (next: FindingFilter) => void; analyzers?: AnalyzerRun[] }) { const set = (key: keyof FindingFilter, value: string) => setFilters({ ...filters, [key]: value }); const tools = [...new Set(analyzers?.map((run) => run.analyzer_id) ?? [])]; return <div className="filters" id="finding-filters"><label>Severity<select value={filters.severity} onChange={(e) => set('severity', e.target.value)}><option value="">All</option>{['critical', 'high', 'medium', 'low', 'info'].map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>Category<input value={filters.category} onChange={(e) => set('category', e.target.value)} placeholder="All categories" /></label><label>Tool<select value={filters.analyzer} onChange={(e) => set('analyzer', e.target.value)}><option value="">All tools</option>{tools.map((tool) => <option value={tool} key={tool}>{analyzerName(tool)}</option>)}</select></label><label>File<input value={filters.path} onChange={(e) => set('path', e.target.value)} placeholder="Any path" /></label><label>Status<select value={filters.status} onChange={(e) => set('status', e.target.value)}><option value="">All</option><option value="new">New</option><option value="persistent">Persistent</option></select></label><label className="filter-search">Search<input value={filters.q} onChange={(e) => set('q', e.target.value)} placeholder="Message or rule" /></label></div>; }

function FindingsPagination({ total, offset, limit, hasMore, onLimit, onPrevious, onNext }: { total: number; offset: number; limit: number; hasMore: boolean; onLimit: (value: number) => void; onPrevious: () => void; onNext: () => void }) { const first = total ? offset + 1 : 0; const last = Math.min(offset + limit, total); return <nav className="findings-pagination" aria-label="Findings pagination"><span>Showing {first}–{last} of {total}</span><label>Rows<select value={limit} onChange={(event) => onLimit(Number(event.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><div><button className="button secondary" onClick={onPrevious} disabled={offset === 0}>Previous</button><button className="button secondary" onClick={onNext} disabled={!hasMore}>Next</button></div></nav>; }

function FindingsTable({ findings, onPreview }: { findings: Finding[]; onPreview: (finding: Finding) => void }) { return <div className="findings-table table-wrap"><table><thead><tr><th scope="col">Severity</th><th scope="col">Finding</th><th scope="col">File</th><th scope="col">Tool</th><th scope="col">Status</th></tr></thead><tbody>{findings.map((finding) => <tr key={finding.id || finding.fingerprint}><td><span className={`severity ${finding.severity}`}>{finding.severity}</span></td><td className="finding-summary"><strong>{finding.title ?? finding.rule_id ?? 'Finding'}</strong><span className="finding-message">{finding.message}</span>{finding.remediation && <span className="finding-remediation">Fix: {finding.remediation}</span>}{finding.documentation_url && <a href={finding.documentation_url} target="_blank" rel="noreferrer">Rule docs</a>}</td><td>{finding.relative_path && finding.id ? <button type="button" className="finding-file" onClick={() => onPreview(finding)} aria-label={`Preview ${findingLocation(finding)}`}><code>{findingLocation(finding)}</code></button> : <code>{findingLocation(finding)}</code>}</td><td><span className="badge">{finding.analyzer_id}</span>{finding.rule_id && <code>{finding.rule_id}</code>}</td><td>{finding.status ? <span className="status-text">{finding.status}</span> : '—'}</td></tr>)}</tbody></table></div>; }
