import { useState } from 'react';
import { api } from '../api';
import type { Notice } from '../lib/notice';
import { message } from '../lib/notice';
import { useLoad } from '../hooks/useLoad';
import { ConfirmationDialog } from '../components/dialogs';

export function SettingsPage({ notify }: { notify: (n: Notice) => void }) {
  const meta = useLoad(api.meta, []); const settings = useLoad(api.settings, []); const [saving, setSaving] = useState(false); const [stopOpen, setStopOpen] = useState(false); const [stopping, setStopping] = useState(false);
  async function save(input: { offline?: boolean; open_browser?: boolean }) { setSaving(true); try { await api.saveSettings(input); await settings.reload(); } catch (e) { notify({ kind: 'error', text: message(e) }); } finally { setSaving(false); } }
  async function stop() { setStopping(true); try { await api.stopServer(); setStopOpen(false); notify({ kind: 'info', text: 'Blunt Code is stopping. You can close this tab.' }); } catch (e) { notify({ kind: 'error', text: message(e) }); setStopping(false); } }
  return <div className="page"><header className="page-heading"><div><p className="eyebrow">Settings</p><h1>Application settings</h1><p>Blunt Code keeps configuration small and local.</p></div></header><div className="settings-list"><section><h2>General</h2><div className="setting"><div><h3>Open browser automatically</h3><p>Open the local interface when Blunt Code starts.</p></div><button className="button secondary" disabled={settings.loading || saving} onClick={() => void save({ open_browser: !(settings.data?.open_browser ?? true) })}>{settings.data?.open_browser ?? true ? 'Browser opens on launch' : 'Browser stays closed'}</button></div><div className="setting"><div><h3>Offline mode</h3><p>Do not download tools or check for updates. Installed tools can still scan local workspaces.</p></div><button className="button secondary" disabled={settings.loading || saving} onClick={() => void save({ offline: !(settings.data?.offline ?? false) })}>{settings.data?.offline ? 'Offline mode on' : 'Offline mode off'}</button></div></section><section><h2>Analysis</h2><Setting label="Default scan profile" description="Workspace scans use the saved profile unless you choose another profile." value="Workspace managed" /><Setting label="Include style findings" description="Style and formatting findings can be configured with workspace rules." value="Workspace managed" /></section><section><h2>Privacy</h2><Setting label="Telemetry" description="Blunt Code does not send usage analytics or repository data to a cloud service." value="Disabled" /><Setting label="Data directory" description="Application state, tool installs, and scan history are kept on this computer." value={meta.data?.data_directory ?? (meta.loading ? 'Loading…' : 'Available from local metadata')} /></section><section><h2>Server</h2><div className="setting danger-setting"><div><h3>Stop local server</h3><p>End this Blunt Code session. Any active scan will be cancelled; your saved workspaces and reports stay on this computer.</p></div><button className="button danger" onClick={() => setStopOpen(true)}>Stop server</button></div></section></div>{stopOpen && <ConfirmationDialog title="Stop Blunt Code?" description="The local server will stop and this page will disconnect. You can start Blunt Code again whenever you need it." confirmLabel="Stop server" busy={stopping} onCancel={() => setStopOpen(false)} onConfirm={stop} />}</div>;
}

function Setting({ label, description, value }: { label: string; description: string; value: string }) { return <div className="setting"><div><h3>{label}</h3><p>{description}</p></div><span>{value}</span></div>; }
